FROM jeguzzi/ros:armhf-melodic-ros-dev
MAINTAINER Jerome Guzzi "jerome@idsia.ch"

RUN echo  "deb-src http://gb.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse"  >> /etc/apt/sources.list
RUN echo  "deb-src http://gb.archive.ubuntu.com/ubuntu/ xenial-updates main restricted universe multiverse" >> /etc/apt/sources.list
RUN echo  "deb-src http://gb.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse" >> /etc/apt/sources.list


RUN apt-get update && apt-get install -y \
    # python-pygame \
    automake \
    libtool \
    python-pip \
    python-cairo \
    gir1.2-rsvg-2.0 \
    python-gi-cairo \
    ros-melodic-dynamic-reconfigure \
    ros-melodic-cv-bridge \
    ros-melodic-image-transport-plugins \
    swig3.0  \
    && apt-get -y build-dep python-pygame \
    && rm -rf /var/lib/apt/lists/*


RUN git clone https://github.com/hardkernel/WiringPi2-Python.git /tmp/WiringPi2-Python && \
    cd /tmp/WiringPi2-Python && \
    git submodule init && \
    git submodule update && \
    swig3.0 -python -threads wiringpi.i && \
    python2 setup.py build install && \
    cd / && rm -r /tmp/WiringPi2-Python


RUN git clone https://github.com/kergoth/tslib.git /tmp/tslib && \
    cd /tmp/tslib && \
    ./autogen.sh && \
    ./configure && \
    make && \
    make install && \
    cd / && rm -r /tmp/tslib

RUN pip install pygame evdev numpy

COPY . src/screen

RUN catkin build
